-- ============================================================================
-- MIGRACIÓN 0084: NOTICIAS DEL FEED
--
-- INSTRUCCIONES:
-- 1. Abre: https://supabase.com/dashboard
-- 2. SQL Editor → Nueva query
-- 3. Copia TODO este contenido
-- 4. Pega en el editor
-- 5. Click RUN
-- 6. ¡Listo!
-- ============================================================================

-- Tabla: noticias_feed
CREATE TABLE IF NOT EXISTS noticias_feed (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club_id BIGINT NOT NULL REFERENCES clubes(id) ON DELETE CASCADE,
  usuario_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  titulo VARCHAR(120) NOT NULL,
  descripcion TEXT,
  imagen_url VARCHAR,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  activo BOOLEAN DEFAULT TRUE
);

-- RLS: Leer todas las noticias activas
ALTER TABLE noticias_feed ENABLE ROW LEVEL SECURITY;

CREATE POLICY "noticias_feed_read_all" ON noticias_feed
  FOR SELECT
  USING (activo = TRUE);

-- RLS: Admin del club puede crear/editar/borrar sus noticias
CREATE POLICY "noticias_feed_admin" ON noticias_feed
  FOR ALL
  USING (
    club_id IN (
      SELECT club_id FROM usuarios
      WHERE id = auth.uid() AND rol IN ('admin', 'super_admin')
    )
  );

-- Índices
CREATE INDEX IF NOT EXISTS idx_noticias_feed_club_activas
  ON noticias_feed(club_id, activo, creado_en DESC);

-- ───────────────────────────────────────────────────────────────────────────
-- FUNCIÓN RPC PARA CREAR NOTICIA
-- ───────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn_crear_noticia_feed(
  p_club_id BIGINT,
  p_titulo VARCHAR,
  p_descripcion TEXT,
  p_imagen_url VARCHAR DEFAULT NULL
)
RETURNS TABLE (
  id BIGINT,
  titulo VARCHAR,
  creado_en TIMESTAMP WITH TIME ZONE
) AS $$
DECLARE
  v_usuario_id UUID;
  v_es_admin BOOLEAN;
BEGIN
  v_usuario_id := auth.uid();
  IF v_usuario_id IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  SELECT EXISTS(
    SELECT 1 FROM usuarios
    WHERE id = v_usuario_id
      AND club_id = p_club_id
      AND rol IN ('admin', 'super_admin')
  ) INTO v_es_admin;

  IF NOT v_es_admin THEN
    RAISE EXCEPTION 'No eres admin de este club';
  END IF;

  INSERT INTO noticias_feed (
    club_id, usuario_id, titulo, descripcion, imagen_url, activo
  ) VALUES (
    p_club_id, v_usuario_id, p_titulo, p_descripcion, p_imagen_url, TRUE
  )
  RETURNING noticias_feed.id, noticias_feed.titulo, noticias_feed.creado_en;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION fn_crear_noticia_feed TO authenticated;

-- ============================================================================
-- ✅ ¡MIGRACIÓN COMPLETA!
-- ============================================================================
