export { ConfiguracionLayout } from './ConfiguracionLayout';
export { MarcaPage } from './marca/MarcaPage';
export { UsuariosPage } from './usuarios/UsuariosPage';
export { CanchasPage } from './canchas/CanchasPage';
export { HorariosPage } from './horarios/HorariosPage';
export { TarifasPage } from './tarifas/TarifasPage';
export { ProfesoresPage } from './profesores/ProfesoresPage';
export { ClasesPage } from './clases/ClasesPage';
export { ProductosPage } from './productos/ProductosPage';
